version: '3'

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data.json:/app/data.json
      - ./users.json:/app/users.json
      - ./html_exports:/app/html_exports
    restart: always
    environment:
      - PYTHONUNBUFFERED=1  # Para melhorar a legibilidade dos logs