[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "streamlit>=1.45.0",
    "twilio>=9.6.0",
    "xlsxwriter>=3.2.3",
]
